name: .NET Build

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
  workflow_dispatch:
    
jobs:

  build:

    runs-on: ubuntu-latest  # For a list of available runner types, refer to
                             # https://help.github.com/en/actions/reference/workflow-syntax-for-github-actions#jobsjob_idruns-on

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    # Execute all unit tests in the solution
    - name: .NET build and publish
      run: |
        dotnet restore
        dotnet build -c Release
        dotnet test -c Release
        dotnet publish -c Release -o /dist
